name: Verify

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3.0-preview1'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    name: ${{ matrix.os }} - Ruby ${{ matrix.ruby }}

    env:
      COVERALLS_SKIP: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libpcap-dev

      - name: Setup Ruby
        env:
          BUNDLE_WITHOUT: "coverage development"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Run tests
        run: |
          bundle install
          bundle exec rspec

